name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/ddk-coder

jobs:
  build:
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    runs-on:
      - self-hosted
      - Linux
      - X64
      - dmz
    outputs:
      image_tag: ${{ steps.prep.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare image tag
        id: prep
        run: |
          echo "tag=test-image:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ steps.prep.outputs.tag }}
          build-args: |
            BUILD_VER=${{ github.sha }}
            PHP_VER=${{ vars.PHP_VER }}
            COMPOSER_VER=${{ vars.COMPOSER_VER }}
            CODER_VER=${{ vars.CODER_VER }}

  test:
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on:
      - self-hosted
      - Linux
      - X64
      - dmz
    steps:
      - name: Run PHPCS tests
        run: |
          docker run --rm ${{ needs.build.outputs.image_tag }} phpcs --version

  publish:
    if: github.event_name != 'pull_request'
    runs-on:
      - self-hosted
      - Linux
      - X64
      - dmz
    steps:
      - name: Get version info
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "is_tag=true" >> $GITHUB_OUTPUT
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          else
            echo "is_tag=false" >> $GITHUB_OUTPUT
            echo "version=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push (for tags)
        if: steps.version.outputs.is_tag == 'true'
        run: |
          COMMIT_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.commit_sha }}"
          VERSION_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"

          echo "Pulling image with commit SHA..."
          docker pull $COMMIT_TAG

          echo "Tagging with version..."
          docker tag $COMMIT_TAG $VERSION_TAG

          echo "Pushing version tag..."
          docker push $VERSION_TAG

      - name: Build and Push (for branches)
        if: steps.version.outputs.is_tag == 'false'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          builder: ${{ vars.DOCKER_BUILDER_NAME }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_VER=${{ steps.version.outputs.version }}
            PHP_VER=${{ vars.PHP_VER }}
            COMPOSER_VER=${{ vars.COMPOSER_VER }}
            CODER_VER=${{ vars.CODER_VER }}
