name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/ddk-coder

jobs:
  build:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - dmz
    outputs:
      image_tag: ${{ steps.prep.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare image tag
        id: prep
        run: |
          echo "tag=test-image:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ steps.prep.outputs.tag }}
          build-args: |
            BUILD_VER=${{ github.sha }}
            PHP_VER=${{ vars.PHP_VER }}
            COMPOSER_VER=${{ vars.COMPOSER_VER }}
            CODER_VER=${{ vars.CODER_VER }}

  test:
    needs: build
    runs-on:
      - self-hosted
      - Linux
      - X64
      - dmz
    steps:
      - name: Run PHPCS tests
        run: |
          docker run --rm ${{ needs.build.outputs.image_tag }} phpcs -V

  publish:
    needs: [build, test]
    if: github.event_name != 'pull_request'
    runs-on:
      - self-hosted
      - Linux
      - X64
      - dmz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set BUILD_VER
        id: build_ver
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ vars.DOCKER_BUILDER_NAME }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_VER=${{ steps.build_ver.outputs.version }}
            PHP_VER=${{ vars.PHP_VER }}
            COMPOSER_VER=${{ vars.COMPOSER_VER }}
            CODER_VER=${{ vars.CODER_VER }}
